### ISSUE TITLE
一个补充

### ISSUE THREAD

**Issue by super-buster** [luhuisicnu/The-Flask-Mega-Tutorial-zh#20]
您好！非常感谢你的这份翻译，我在阅读原文邮件这一章（第10章）， Sending a Password Reset Email 这个小结中，作者在最后有一段话没有翻译出来。我认为那段是比较重要的一部分。能否补上那一部分？

下面是我的翻译：
但是在这两个模版中，由url_for()生成的reset_password链接还没有路由去处理。
我们将在下一部分添加。这里还有一个新的参数_external=True。使用url_for()生成的
链接默认都是相对路径的URL。举一个，url_for('user', username='susan')，
它返回的应该是 /user/susan. 在网页中这通常是有效的，因为浏览器从当前页面获取url的其余部分。
但是当我们用电子邮件来发送一个邮件时，这个上下文就不存在了，所以我们必须使用url的全路径。
当_external=True作为一个参数传递时，url的全路径被产生，所以在之前那个例子中，使用url_for将会
返回http://localhost:5000/user/susan, 或者在域名上部署应用程序的相应url。

**Comment by luhuisicnu** [comment]
感谢提示，如果想你的贡献被合并，可以提pr，本次我就先自行添加了。
