### ISSUE TITLE
第十六章可以加一点提示吗

### ISSUE THREAD

**Issue by miaoweiwei** [luhuisicnu/The-Flask-Mega-Tutorial-zh#42]
elasticsearch服务的版本不能好像在搜索的时候返回的json也不同，python项目中的elasticsearch版本不同使用search()这个方法的参数也不一样。
我的elasticsearch服务版本是7.2.0，python项目中的elasticsearch版本是7.0.2。使用下面这条语句会报错如下，
es.search(index='my_index', doc_type='my_index',body={'query': {'match': {'text': 'this test'}}})
Traceback (most recent call last):
File "", line 1, in 
File "D:\Myproject\Python\Flask\Flask-Microblog\venv\lib\site-packages\elasticsearch\client\utils.py", line 84, in _wrapped
return func(*args, params=params, **kwargs)
TypeError: search() got an unexpected keyword argument 'doc_type'
我的elasticsearch服务版本是7.2.0，python项目中的elasticsearch版本是7.0.2。使用这条语句就不报错
es.search(index='my_index', body={'query': {'match': {'text': 'this test'}}})

**Comment by luhuisicnu** [comment]
是的，es版本变更很快。

**Comment by luhuisicnu** [comment]
已加译注
