### ISSUE TITLE
第十三章用户通知的默认时间设置

### ISSUE THREAD

**Issue by furuiyang0715** [luhuisicnu/The-Flask-Mega-Tutorial-zh#43]
![image](https://user-images.githubusercontent.com/45279334/62345487-363e9800-b525-11e9-9aad-40c011e71b37.png)
这样写没有在数据库生成默认的时间字段 （截图中 time() 应为 time）

尝试显式传入可行
![image](https://user-images.githubusercontent.com/45279334/62345595-8289d800-b525-11e9-8c52-933fdd609a36.png)

查找到的相关：
https://blog.csdn.net/weixin_33672109/article/details/88098979

**Comment by luhuisicnu** [comment]
ORM设置默认时间和数据库设置默认时间是两回事，不能混为一谈。
