### ISSUE TITLE
无法按照文档描述，成功创建视图关系

### ISSUE THREAD

**Issue by whsheng** [luhuisicnu/The-Flask-Mega-Tutorial-zh#48]
按照第四章的内容，在models中为User、Post类添加了相关代码，但在试图给User添加信息的时候报错，提示如下：
`sqlalchemy.orm.exc.LoaderStrategyException: Can't find strategy (('lazy', 'dynamci'),) for User.posts`

**Comment by Pawn0w0** [comment]
dynamic

**Comment by tangkehu** [comment]
兄弟你写错了，是'dynamic'不是'dynamci'。
