### ISSUE TITLE
第十章发送邮箱不带token

### ISSUE THREAD

**Issue by kuafuliu** [luhuisicnu/The-Flask-Mega-Tutorial-zh#49]
你好大神，开发中碰到下面问题，请不吝赐教
--------------------------------------------------------
接收邮件内容中无token,如下：
Dear susan,

To reset your password click here .

Alternatively, you can paste the following link in your browser's address bar:

http://127.0.0.1:5000/reset_password/

If you have not requested a password reset simply ignore this message.

Sincerely,

The Microblog Team
----------------------------------------------------------
但是在方法中打印，有携带token：

http://127.0.0.1:5000/reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNTc4MzA1NTU4Ljg4MDAyNzN9.QfVnEBNr3vyXpRVUvd5GZyPcTIC5fHn3dtoI6P84O-I

------------------------------------------------------------------
代码：
token = user.get_reset_password_token()
    url = url_for('reset_password', token=token, _external=True)
    print(url)
    send_email('[Microblog] 重置密码',
               sender=app.config['ADMINS'][0],
               recipients=[user.email],
               text_body=render_template('email/reset_password.txt', user=user, url=url),
               html_body=render_template('email/reset_password.html', user=user, url=url)
               )

请给予回复，谢谢

**Comment by luhuisicnu** [comment]
print(render_template('email/reset_password.txt', user=user, url=url))
print(render_template('email/reset_password.html', user=user, url=url))
这两个才能看邮件中的内容，另外，如果不是勘误，可以直接使用源代码和自己的代码比对，得到查错方向，不要在issue中提问。
