### ISSUE TITLE
代码效果与教程不符

### ISSUE THREAD

**Issue by S-HuaBomb** [luhuisicnu/The-Flask-Mega-Tutorial-zh#51]
我在[第十三章：国际化和本地化.md](https://github.com/luhuisicnu/The-Flask-Mega-Tutorial-zh/blob/master/docs/%e7%ac%ac%e5%8d%81%e4%b8%89%e7%ab%a0%ef%bc%9a%e5%9b%bd%e9%99%85%e5%8c%96%e5%92%8c%e6%9c%ac%e5%9c%b0%e5%8c%96.md)的[翻译日期和时间](https://github.com/luhuisicnu/The-Flask-Mega-Tutorial-zh/blob/master/docs/%e7%ac%ac%e5%8d%81%e4%b8%89%e7%ab%a0%ef%bc%9a%e5%9b%bd%e9%99%85%e5%8c%96%e5%92%8c%e6%9c%ac%e5%9c%b0%e5%8c%96.md#%E7%BF%BB%E8%AF%91%E6%97%A5%E6%9C%9F%E5%92%8C%E6%97%B6%E9%97%B4)这个部分做了跟教程一样的配置，所有我翻译的文本都显示了中文，可是moment.js显示的时间还是英文（我翻译包是中文而且是第一语言，源代码中都是英文），即使我再次`update`和`compile`翻译包之后还是英文：
![en not zh](https://img-blog.csdnimg.cn/20200214223423513.png)
问题有两个：
* 作者的教程中显示了西班牙语，可是他并没有把hours、ago翻译成西班牙语（至少教程中没有说，源代码的`*.po`文件中也没有），那个日期和时间是自动翻译的？
* 问题是不是出在第一个问题？

**Comment by nullnan** [comment]
moment.js格式要在模板里设置，在引入的地方加上{{ moment.locale('zh-cn') }}就行

**Comment by S-HuaBomb** [comment]
我在 base.html 里引入 `moment.js` 的地方加上了：
```
{% block scripts %}
<!-- 引入moment.js库 -->
    {{ super() }}
    {{ moment.include_moment() }}
    <!-- 日期和时间都与文本使用相同的语言 -->
    {{ moment.lang(g.locale) }}
    {{ moment.locale('zh-cn') }}
    ......
{% block scripts %}
```
🎉  🎉  🎉 
成功了！
![james.png](https://img-blog.csdnimg.cn/20200302221640873.png)

我又发现 `g.locale` 取的是 Babel 的 `get_locale()`，而它不允许有 letters 以外的字符，所以它无法返回 `zh-cn`，而是 `zh`，所以在 `route.py` 中的 `before_request()` 加了个判断：
```python
@bp.before_app_request
def before_request():
    ......
    # 将语言环境添加到g对象, 以便我可以从base模板中访问它,并以正确的语言配置moment.js
    locale_lang = str(get_locale())
    if 'zh' in locale_lang:  # 浏览器认 zh-cn 而不是 zh
        locale_lang = 'zh-cn'
    g.locale = locale_lang
```
