### ISSUE TITLE
第十一章 邮件 密码重置处

### ISSUE THREAD

**Issue by KpLi0rn** [luhuisicnu/The-Flask-Mega-Tutorial-zh#52]
user.set_password(form.password.data)
db.session.commit()
源代码是这样 
但是这是有问题第 我学习的过程中发现像之前的代码是有问题的 
我们应该
user.set_password(form.password.data)
db.session.add(user)   
db.session.commit()

**Comment by S-HuaBomb** [comment]
作者在[第六章：个人主页和头像.md](https://github.com/luhuisicnu/The-Flask-Mega-Tutorial-zh/blob/master/docs/%e7%ac%ac%e5%85%ad%e7%ab%a0%ef%bc%9a%e4%b8%aa%e4%ba%ba%e4%b8%bb%e9%a1%b5%e5%92%8c%e5%a4%b4%e5%83%8f.md)中的[记录用户的最后访问时间](https://github.com/luhuisicnu/The-Flask-Mega-Tutorial-zh/blob/master/docs/%e7%ac%ac%e5%85%ad%e7%ab%a0%ef%bc%9a%e4%b8%aa%e4%ba%ba%e4%b8%bb%e9%a1%b5%e5%92%8c%e5%a4%b4%e5%83%8f.md#%E8%AE%B0%E5%BD%95%E7%94%A8%E6%88%B7%E7%9A%84%E6%9C%80%E5%90%8E%E8%AE%BF%E9%97%AE%E6%97%B6%E9%97%B4)解释了:
> 如果你想知道为什么在提交之前没有 `db.session.add()`，考虑在引用 `current_user` 时，`Flask-Login` 将调用用户加载函数，该函数将运行一个数据库查询并将目标用户添加到数据库会话中。所以你可以在这个函数中再次添加用户，但是这不是必须的，因为它已经在那里了。
