### ISSUE TITLE
第四章：数据库.md[直接运行会报错]

### ISSUE THREAD

**Issue by ZuhuiMa** [luhuisicnu/The-Flask-Mega-Tutorial-zh#53]
在第四章中：

进入Python交互式环境后，导入数据库实例和模型：

>>> from app import db
>>> from app.models import User, Post
开始阶段，创建一个新用户：

>>> u = User(username='john', email='john@example.com')
>>> db.session.add(u)
>>> db.session.commit()

运行到commit命令的时候会报错："sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user"
需要在创建数据库会话之前使用命令"db.create_all()"调用app/models里面自己定义的表，否则会找不到目标表报错

**Comment by luhuisicnu** [comment]
文章前半部分，正是数据库迁移部分的配置，包括了创建和字段变更的迁移能力，如果没有照做的话，就会没有表。

**Comment by ZuhuiMa** [comment]
对不起。。我的错
